/*
 * Filename: sc_input_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signal class for clock input
 * name: sc_Input
 * shortname: Input
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_input_type.h"



/* USER CODE START SC_INPUT_INCLUDE */
#include "stdlib.h"
/* USER CODE END SC_INPUT_INCLUDE */




/* USER CODE START SC_INPUT_USERDEFINITIONS */

/* USER CODE END SC_INPUT_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_INPUT signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_INPUT_driverIn(SC_INPUT_data_t *const data)
{
	/* USER CODE START driverInSC_INPUT */
    static uint16_t KeyLeft_Button_1_flag = 0;
    static uint16_t KeyLeft_Button_2_flag = 0;   
    static uint16_t tickevent   =   0; 
    static uint16_t tickevent_long   =   0; 
    
    data->m_ev = EV_NONE;
    tickevent++;
    

    if((tickevent % 5) == 0) // 250ms
    {
        data->m_ev = EV_250MS; 
    } 
    if((tickevent % 1200) == 0) // 1 minute
    {
        data->m_ev = EV_1MIN;
        tickevent = 0;
    }
 
    if(KeyLeft_Button_1_Read() == 1) // left button
    {
        KeyLeft_Button_1_flag = 1;
    }
    if(KeyRight_Button_2_Read() == 1) // right button
    {
        KeyLeft_Button_2_flag = 1;
        tickevent_long++;
    }
    
    if(KeyLeft_Button_1_Read() == 0 && KeyLeft_Button_1_flag == 1)
    {
        data->m_ev = EV_KEYLEFT;        
        KeyLeft_Button_1_flag = 0; 
    }  
    else if(KeyRight_Button_2_Read() == 0 && KeyLeft_Button_2_flag == 1)
    {
        if(tickevent_long < 20)
        {
            data->m_ev = EV_KEYRIGHT;
            KeyLeft_Button_2_flag = 0;
            tickevent_long = 0;
        }
        else if(tickevent_long >= 20)
        {
            data->m_ev = EV_KEYRIGHTLONGPRESS;  // long press
            KeyLeft_Button_2_flag = 0;
            tickevent_long = 0;
        }
    }
    

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_INPUT */
}



