
/*
 * Filename: swc_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component for control logic
 */

#ifndef _H_DEFINE_SWC_CONTROL
#define _H_DEFINE_SWC_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CONTROL_INCLUDES */

/* USER CODE END SWC_CONTROL_INCLUDES */



/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */


/*
 * component: swc_Control
 * cycletime: 0
 * description: Runnable for control logic
 * events: ev_onData
 * name: CONTROL_Clock_control_run
 * shortname: Clock_control
 * signalIN: so_ButtonEvent
 * signalOUT: so_Control
 * task: tsk_control
 */
void CONTROL_Clock_control_run(RTE_event ev);


#endif