/*
 * Filename: swc_display.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for display
 * name: swc_Display
 * shortname: Display
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_display.h"



/* USER CODE START SWC_DISPLAY_INCLUDE */

/* USER CODE END SWC_DISPLAY_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_DISPLAY_USERDEFINITIONS */
#include "clock.h"
/* USER CODE END SWC_DISPLAY_USERDEFINITIONS */



/*
 * component: swc_Display
 * cycletime: 250
 * description: Runnable for TFT disply
 * events: 
 * name: DISPLAY_Clock_display_run
 * shortname: Clock_display
 * signalIN: so_Control
 * signalOUT: so_DisplayTFT
 * task: tsk_io
 */
void DISPLAY_Clock_display_run(RTE_event ev){
	
	/* USER CODE START DISPLAY_Clock_display_run */
    SC_DISPLAY_data_t    tft_data  =   SC_DISPLAY_INIT_DATA;    
    SC_CONTROL_data_t   control_data    = SC_CONTROL_INIT_DATA;
    
    control_data    =   RTE_SC_CONTROL_get(&SO_CONTROL_signal);
    
    tft_data.hour     =   control_data.hour;
    tft_data.minute   =   control_data.minute;
    
    RTE_SC_DISPLAY_set(&SO_DISPLAYTFT_signal, tft_data);
    RTE_SC_DISPLAY_pushPort(&SO_DISPLAYTFT_signal);
    /* USER CODE END DISPLAY_Clock_display_run */
}

/* USER CODE START SWC_DISPLAY_FUNCTIONS */

/* USER CODE END SWC_DISPLAY_FUNCTIONS */

