/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component for control logic
 * name: swc_Control
 * shortname: Control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"



/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */
#include "clock.h"
/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_Control
 * cycletime: 0
 * description: Runnable for control logic
 * events: ev_onData
 * name: CONTROL_Clock_control_run
 * shortname: Clock_control
 * signalIN: so_ButtonEvent
 * signalOUT: so_Control
 * task: tsk_control
 */
void CONTROL_Clock_control_run(RTE_event ev){
	
	/* USER CODE START CONTROL_Clock_control_run */
    
    SC_INPUT_data_t rxEvent;
    
    rxEvent = RTE_SC_INPUT_get(&SO_BUTTONEVENT_signal);
    
    if(rxEvent.m_ev != EV_NONE)
    {
        ProcessEvent(rxEvent.m_ev);
    }

    /* USER CODE END CONTROL_Clock_control_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

